name: replay
description: "Replay meeting note-taker mobile client"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.1
  record: ^5.0.5
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.4.0
  http_parser: ^4.0.2
  google_sign_in: ^6.2.1
  file_picker: ^8.0.0+1
  flutter_foreground_task: ^8.0.0
  permission_handler: ^11.3.0
  flutter_secure_storage: ^9.0.0
  flutter_markdown: ^0.7.3
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/env/

dependency_overrides:
  record_linux:
    path: third_party/record_linux

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/sound-wave.png"
